apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: nginx
    image: cgr.dev/chaindguard/nginx:latest
    ports:
    - containerPort: 8080