apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1-container
    image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "res-intensive"
    effect: "NoSchedule"